[package]
name = "ProjectHostServer"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12.9" , features = ["blocking", "json"] }
serde = { version = "1.0.216", features = ["derive"] }
base64 = "0.22.1"
serde_json = "1.0.133"