### GET request to example server
POST 127.0.0.1:1313/index.html
Host: html-test.quantumadmin.esporterz.com

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>test site 2!</title>
</head>
<body>
    this is an updated! test site
</body>
</html>
###